version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: taskmanagerdb
      MYSQL_ROOT_PASSWORD: gunther22
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pgunther22"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USER=root
      - DB_PASS=gunther22

volumes:
  db_data:
